#  Ordinal Encoding

In [2]:
import pandas as pd 
import numpy as np

In [44]:
df = pd.read_csv("dataset\Customer Purchase.csv")
df.sample(5)

Customer ID  Age  Gender Education   Review Purchased
30         1051   73    Male        UG  Average        No
12         1033   51    Male    School     Poor        No
5          1026   31  Female    School  Average       Yes
37         1058   94    Male        PG  Average       Yes
44         1065   77  Female        UG  Average        No

In [45]:
df = df.iloc[:,3:]


In [46]:
df.sample(5)

Education Review Purchased
40    School   Good        No
46        PG   Poor        No
47        PG   Good       Yes
25    School   Good        No
28    School   Poor        No

In [50]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,Y_train ,Y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1:],test_size =0.2 ,random_state= 2)


In [51]:
X_train.head()

Education   Review
24        PG  Average
48        UG     Good
17        UG     Poor
12    School     Poor
27        PG     Poor

In [53]:
# Ordinal Encoding

from sklearn.preprocessing import OrdinalEncoder

creating object so the ordered of encoding is from low to High

In [57]:
oe = OrdinalEncoder(categories=[['School','UG','PG'],['Poor','Average','Good']])

In [63]:
#oe.fit(X_train)



In [68]:
#X_train =oe.transform(X_train)


In [66]:
X_train

array([[2., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [0., 2.]])

# Label Encoding 

label encoding used for target Values or outcome

In [70]:
from sklearn.preprocessing import LabelEncoder 

In [73]:
le = LabelEncoder()


In [74]:
le.fit(Y_train)

C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [75]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [76]:
Y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0])

In [78]:
print(le.classes_)

['No' 'Yes']


# OneHot Encoding 

In [80]:
import numpy as np
import pandas as pd  

In [82]:
df =pd.read_csv('dataset\cars.csv')


In [83]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [84]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [86]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [87]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

ONEHOT ENCODING using Pandas  - used when data analysis but not for Ml project because it change the position of column every time u run it 

In [88]:
pd.get_dummies(df,columns = ['fuel','owner'])

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000     False         True     False   
1       Skoda     120000         370000     False         True     False   
2       Honda     140000         158000     False        False     False   
3     Hyundai     127000         225000     False         True     False   
4      Maruti     120000         130000     False        False     False   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000     False        False     False   
8124  Hyundai     119000         135000     False         True     False   
8125   Maruti     120000         382000     False         True     False   
8126     Tata      25000         290000     False         True     False   
8127     Tata      25000         290000     False         True     False   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0           False               True                       False   
1           False              False                       False   
2            True              False                       False   
3           False               True                       False   
4            True               True                       False   
...           ...                ...                         ...   
8123         True               True                       False   
8124        False              False                        True   
8125        False               True                       False   
8126        False               True                       False   
8127        False               True                       False   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                  False                 False              False  
1                   True                 False              False  
2                  False                 False               True  
3                  False                 False              False  
4                  False                 False              False  
...                  ...                   ...                ...  
8123               False                 False              False  
8124               False                 False              False  
8125               False                 False              False  
8126               False                 False              False  
8127               False                 False              False  

[8128 rows x 12 columns]

K-1 OneHot Encoding

In [90]:
pd.get_dummies(df,columns = ['fuel','owner'] ,drop_first = True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000         True     False        False   
1       Skoda     120000         370000         True     False        False   
2       Honda     140000         158000        False     False         True   
3     Hyundai     127000         225000         True     False        False   
4      Maruti     120000         130000        False     False         True   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000        False     False         True   
8124  Hyundai     119000         135000         True     False        False   
8125   Maruti     120000         382000         True     False        False   
8126     Tata      25000         290000         True     False        False   
8127     Tata      25000         290000         True     False        False   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                          False               False                 False   
1                          False                True                 False   
2                          False               False                 False   
3                          False               False                 False   
4                          False               False                 False   
...                          ...                 ...                   ...   
8123                       False               False                 False   
8124                        True               False                 False   
8125                       False               False                 False   
8126                       False               False                 False   
8127                       False               False                 False   

      owner_Third Owner  
0                 False  
1                 False  
2                  True  
3                 False  
4                 False  
...                 ...  
8123              False  
8124              False  
8125              False  
8126              False  
8127              False  

[8128 rows x 10 columns]

ONE HOT ENCODING USING SKLEARN 

In [91]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,Y_train,Y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1], test_size = 0.2 ,random_state=2)

In [93]:
X_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [94]:
from sklearn.preprocessing import OneHotEncoder


In [95]:
ohe = OneHotEncoder()

In [110]:
#X_train =ohe.fit_transform(X_train[['fuel','owner']])

In [105]:
X_train.toarray()

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [106]:
X_test = ohe.fit_transform(X_test[['fuel','owner']])

In [107]:
X_train.toarray()

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [112]:
ohe = OneHotEncoder(drop = 'first')

In [113]:
# use of sparse = true
# visit doucementation of OnehotEncoding

OneHot Encoding with frequent Categories

In [114]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [115]:
counts = df['brand'].value_counts()

In [116]:
df['brand'].nunique()
thresold = 100

In [119]:
repl = counts[counts <= thresold].index
print(repl) # brands less thresold value

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')


In [121]:
pd.get_dummies(df['brand'].replace(repl ,'uncomon'))

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
0     False      False  False  False    False     False    True    False   
1     False      False  False  False    False     False   False    False   
2     False      False  False   True    False     False   False    False   
3     False      False  False  False     True     False   False    False   
4     False      False  False  False    False     False    True    False   
...     ...        ...    ...    ...      ...       ...     ...      ...   
8123  False      False  False  False     True     False   False    False   
8124  False      False  False  False     True     False   False    False   
8125  False      False  False  False    False     False    True    False   
8126  False      False  False  False    False     False   False    False   
8127  False      False  False  False    False     False   False    False   

      Skoda   Tata  Toyota  Volkswagen  uncomon  
0     False  False   False       False    False  
1      True  False   False       False    False  
2     False  False   False       False    False  
3     False  False   False       False    False  
4     False  False   False       False    False  
...     ...    ...     ...         ...      ...  
8123  False  False   False       False    False  
8124  False  False   False       False    False  
8125  False  False   False       False    False  
8126  False   True   False       False    False  
8127  False   True   False       False    False  

[8128 rows x 13 columns]