Numpy - Numerical Python


Advantages of Numpy Arrays

  1. Allows several faster operations
  2. Faster Operations

In [1]:
 import numpy as np

List Vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [8]:
python_list =[i for i in range (10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0015326189999989026


In [10]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5
end_time = process_time()

print(end_time - start_time)



0.000146945999999204





Numpy Arrays

In [11]:
#list
list1 = [i for i in range(6)]
print(list1)
type(list1)

[0, 1, 2, 3, 4, 5]


list

In [13]:
#numpy arrays
np_array = np.array([i for i in range(6)])

print(np_array)
type(np_array)

[0 1 2 3 4 5]


numpy.ndarray

In [14]:
# creatin a 1 dimensional array

a = np.array([1,2,3,4,5])
print(a)


[0 1 2 3 4 5]


In [18]:
a.shape  # no. of rows and columns

(6,)

In [16]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
b.shape # no. of rows and columns

(2, 5)

In [20]:
c = np.array([(1,2,3,4,),(7,8,9,10)], dtype = float) # floating point values

print(c)


[[ 1.  2.  3.  4.]
 [ 7.  8.  9. 10.]]




Intial Placholders in Numpy Arrays



In [22]:
# create a numpy array of Zeros
x = np.zeros([4,5])
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:

# create a numpy array of ones
y = np.ones([3,3])
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:

# array of Particular Values
z = np.full((5,4),7)         # ((rows,columns),value)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [28]:
# create an identity matrix

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# create a numpy array with random Values

b = np.random.random((3,5))
print(b)

[[0.47684367 0.71215523 0.37101672 0.50285555 0.02307044]
 [0.16134274 0.94535036 0.49217347 0.75692618 0.46232097]
 [0.43676767 0.18713092 0.19471111 0.93934936 0.62119546]]


In [38]:
# random integer values array with specific range

c = np.random.randint(10,100,(3,4))  # (ranges,(row ,column))
print(c)

[[44 23 10 22]
 [33 56 69 72]
 [83 44 21 57]]


In [40]:
# array of evenly space values
d = np.linspace(10,30,6)   # (start,stop,no. of values)
print(d)

[10. 14. 18. 22. 26. 30.]


In [41]:
# array of evenly spaced values --> specifiy the step

e = np.arange(10,30,6)   # (row,column,step)
print(e)

[10 16 22 28]


In [42]:
# convert a list to a numpy array

list2 =[10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)


[10 20 30 40 50]


numpy.ndarray



Analysing a Numpy Array

In [44]:
c = np.random.randint(10,90,(5,5))
print(c)


[[33 84 11 53 83]
 [47 52 27 11 79]
 [49 11 14 20 41]
 [78 36 14 13 42]
 [53 85 55 34 70]]


In [45]:
# array dimension
c.shape

(5, 5)

In [46]:
# number of dimensions
c.ndim

2

In [47]:
# number of elements in an array
c.size

25

In [48]:
# checking the data type of the values in array
c.dtype

dtype('int64')



Mathematical Operation on an Numpy Array

In [51]:
list1 = [i for i in range(1,6) ]
list2 = [i for i in range(6,11)]
print(list1 + list2)        # concantenate or joins the list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [52]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(10,20,(3,3))



In [53]:
print(a)
print(b)

[[2 4 3]
 [4 8 3]
 [8 5 9]]
[[15 18 12]
 [18 14 19]
 [19 17 11]]


In [57]:
print(a + b)  # values of  both array added
print('-------')
print(a-b)
print('-------')
print(a*b)
print('-------')
print(a/b)

[[17 22 15]
 [22 22 22]
 [27 22 20]]
-------
[[-13 -14  -9]
 [-14  -6 -16]
 [-11 -12  -2]]
-------
[[ 30  72  36]
 [ 72 112  57]
 [152  85  99]]
-------
[[0.13333333 0.22222222 0.25      ]
 [0.22222222 0.57142857 0.15789474]
 [0.42105263 0.29411765 0.81818182]]


In [58]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [61]:
print(a)
print("-------")
print(b)

[[9 1 9]
 [6 2 1]
 [6 1 8]]
-------
[[11 13 12]
 [18 12 12]
 [14 18 15]]


In [65]:
print(np.add(a,b))  # add the values of  array
print('-------')
print( np.subtract(a,b))
print('-------')
print(np.multiply(a,b))

print('-------')
print(np.divide(a,b))


[[20 14 21]
 [24 14 13]
 [20 19 23]]
-------
[[ -2 -12  -3]
 [-12 -10 -11]
 [ -8 -17  -7]]
-------
[[ 99  13 108]
 [108  24  12]
 [ 84  18 120]]
-------
[[0.81818182 0.07692308 0.75      ]
 [0.33333333 0.16666667 0.08333333]
 [0.42857143 0.05555556 0.53333333]]


In [67]:
array = np.random.randint(10,30,(2,3))
print(array)
print(array.shape)

[[12 18 28]
 [20 21 25]]
(2, 3)


In [68]:
# transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[12 20]
 [18 21]
 [28 25]]
(3, 2)


In [69]:
array = np.random.randint(10,30,(2,3))
print(array)
print(array.shape)

[[12 12 19]
 [26 24 24]]
(2, 3)


In [70]:
# another method for transpose
trans2 = array.T
print(trans2)
trans.shape

[[12 26]
 [12 24]
 [19 24]]


(3, 2)

In [72]:
# reshaping a array

a = np.random.randint(0,10,(2,3))
print(a)
a.shape

[[8 1 9]
 [0 0 9]]


(2, 3)

In [73]:
b = a.reshape(3,2)
print(b)
b.shape

[[8 1]
 [9 0]
 [0 9]]


(3, 2)